### PR TITLE
Create GitHub Action for Gatorgrade

### PR DESCRIPTION
**Pull request by burgess01**
# Create GitHub Action for Gatorgrade

## Description
The code in this pull request creates the GitHub action for Gatorgrade. I will work on publishing this to the Marketplace once this is pushed to main. I also included a basic README modeled after the README for the gatorgradle action.

## Type of Change

- [x] Feature
- [ ] Bug fix
- [x] Documentation

## Contributors

- @burgess01 

## Reminder

 - All GitHub Actions should be in a passing state before any pull request is merged.
 - All PRs must be reviewed by at least one team member and one member of the Integration team!
 - Any issues this PR closes are tagged in the description!

### CODE REVIEW

**Review by noorbuchi — CHANGES_REQUESTED** [review]
Thanks for getting this started! Here are some comments/questions that I have

**Review by Michionlion — CHANGES_REQUESTED** [review]
Hi @burgess01! This looks awesome! I have just a few little tweaks I'd like to see, to make the code and documentation more readable and conform to style conventions. Thanks for working on this action! I'm looking forward to seeing it on the marketplace.

**Review by Michionlion — CHANGES_REQUESTED** [review]
Thanks for all those changes! I think this is perfect, except for one tiny change that I didn't catch the first time... 🤦‍♂️ With that fixed you should be good to merge!

**Review by Michionlion — APPROVED** [review]
This looks great!

**Review by laurennevill — APPROVED** [review]
This looks good. Great work, Katie!

**Review by noorbuchi — APPROVED** [review]
Thanks for your work on this @burgess01! Looks great!

**Pull request merged**
